/* Generated by Yosys 0.33 (git sha1 2584903a0, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:1.1-29.10" *)
module add(IN, OUT, clk);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:3.19-3.21" *)
  input [127:0] IN;
  wire [127:0] IN;
  (* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:4.21-4.24" *)
  output [127:0] OUT;
  wire [127:0] OUT;
  (* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:10.9-10.11" *)
  reg R0;
  (* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:10.13-10.17" *)
  reg R0_1;
  (* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:5.11-5.14" *)
  input clk;
  wire clk;
  assign OUT[39] = 16'hd42b >> { _06_, IN[6], IN[14], _00_ };
  assign _00_ = 8'h2b >> { IN[5], IN[13], _01_ };
  assign _01_ = 16'h1117 >> { _05_, _02_, IN[4], IN[12] };
  assign _02_ = 16'hd400 >> { _04_, IN[2], IN[10], _03_ };
  assign _03_ = 16'h1777 >> { IN[8], IN[0], IN[1], IN[9] };
  assign _04_ = 4'h6 >> { IN[3], IN[11] };
  assign _05_ = 4'h8 >> { IN[3], IN[11] };
  assign _06_ = 4'h9 >> { IN[7], IN[15] };
  assign OUT[32] = 4'h6 >> { IN[0], IN[8] };
  assign OUT[33] = 16'h8778 >> { IN[1], IN[9], IN[0], IN[8] };
  assign OUT[34] = 8'h69 >> { IN[2], IN[10], _03_ };
  assign OUT[35] = 16'h2bd4 >> { _04_, IN[2], IN[10], _03_ };
  assign OUT[36] = 16'he11e >> { IN[4], IN[12], _05_, _02_ };
  assign OUT[37] = 8'h69 >> { IN[5], IN[13], _01_ };
  assign OUT[38] = 8'h69 >> { IN[6], IN[14], _00_ };
  (* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:22.2-25.5" *)
  always @(posedge clk)
    R0 <= R0_1;
  (* src = "/home/pmarlowe/Fabric-to-Silicon/fpga_cad_flow/example_designs/simple_fpga_add_test/inputs/add.v:22.2-25.5" *)
  always @(posedge clk)
    R0_1 <= IN[0];
  assign { OUT[127:40], OUT[31:0] } = { 118'hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, R0, R0_1 };
endmodule
